export default {
  title: 'light',

  colors: {
    background: '#F0F0F7',
    primary: '#8257E5',
    primaryLight: '#916BEA',
    primaryLighter: '#9871F5',
    primaryDark: '#774DD6',
    primaryDarker: '#6842C2',
    secundary: '#04D361',
    secundaryDark: '#04BF58',
    titlePrimary: '#FFFFFF',
    textPrimary: '#D4C2FF',
    textTitle: '#32264D',
    textComplement: '#9C98A6',
    textBase: '#6A6180',
    lineWhite: '#E6E6F0',
    inputBackground: '#F8F8FC',
    buttonText: '#FFFFFF',
    deleteButtonText: '#e33d3d',
    buttonDisabled: '#DCDCE6',
    boxBase: '#FFFFFF',
    boxFooter: '#FAFAFC',
  },
};
